# import the required libraries

In [43]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.preprocessing import LabelEncoder

In [44]:
df=pd.read_csv(f'../Data/ai_models_performance.csv')

In [45]:
df.head()

,Model,Context Window,Creator,Intelligence Index,Price (Blended USD/1M Tokens),Speed(median token/s),Latency (First Answer Chunk /s)
0,GPT-5.2 (xhigh),400k,OpenAI,51,$4.81,100,44.29
1,Claude Opus 4.5,200k,Anthropic,49,$10.00,79,1.70
2,Gemini 3 Pro Preview (high),1m,Google,48,$4.50,128,32.19
3,GPT-5.1 (high),400k,OpenAI,47,$3.44,127,26.50
4,Gemini 3 Flash,1m,Google,46,$1.13,224,11.62

# dataset information

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 188 entries, 0 to 187
Data columns (total 7 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Model                            188 non-null    str
 1   Context Window                   188 non-null    str
 2   Creator                          188 non-null    str
 3   Intelligence Index               188 non-null    str
 4   Price (Blended USD/1M Tokens)    188 non-null    str
 5   Speed(median token/s)            188 non-null    int64
 6   Latency (First Answer Chunk /s)  188 non-null    float64
dtypes: float64(1), int64(1), str(5)
memory usage: 10.4 KB

In [47]:
df.describe()

       Speed(median token/s)  Latency (First Answer Chunk /s)
count             188.000000                       188.000000
mean               89.765957                         3.313351
std                92.515404                        12.711482
min                 0.000000                         0.000000
25%                14.500000                         0.217500
50%                72.000000                         0.520000
75%               127.250000                         1.082500
max               550.000000                       113.010000

In [48]:
df.shape

(188, 7)

In [49]:
df.columns

Index(['Model', 'Context Window', 'Creator', 'Intelligence Index',
       'Price (Blended USD/1M Tokens)', 'Speed(median token/s)',
       'Latency (First Answer Chunk /s)'],
      dtype='str')

# check for null values

In [51]:
df.isna().sum()

Model                              0
Context Window                     0
Creator                            0
Intelligence Index                 0
Price (Blended USD/1M Tokens)      0
Speed(median token/s)              0
Latency (First Answer Chunk /s)    0
dtype: int64

# check for duplicated values

In [52]:
df.duplicated().sum()

np.int64(1)

In [53]:
df.drop_duplicates()

,Model,Context Window,Creator,Intelligence Index,Price (Blended USD/1M Tokens),Speed(median token/s),Latency (First Answer Chunk /s)
0,GPT-5.2 (xhigh),400k,OpenAI,51,$4.81,100,44.29
1,Claude Opus 4.5,200k,Anthropic,49,$10.00,79,1.70
2,Gemini 3 Pro Preview (high),1m,Google,48,$4.50,128,32.19
3,GPT-5.1 (high),400k,OpenAI,47,$3.44,127,26.50
4,Gemini 3 Flash,1m,Google,46,$1.13,224,11.62
...,...,...,...,...,...,...,...
183,Grok Voice Agent,32k,xAI,--,$0.00,0,0.00
184,Olmo 3.1 32B Think,66k,Allen Institute for AI,--,$0.00,60,0.54
185,Cogito v2.1,128k,Deep Cogito,--,$1.25,74,0.38
186,Mi:dm K 2.5 Pro Preview,128k,Korea Telecom,--,$0.00,0,0.00
187,Doubao-Seed-1.8,256k,ByteDance Seed,--,$0.15,0,0.00

In [50]:
df.head()

,Model,Context Window,Creator,Intelligence Index,Price (Blended USD/1M Tokens),Speed(median token/s),Latency (First Answer Chunk /s)
0,GPT-5.2 (xhigh),400k,OpenAI,51,$4.81,100,44.29
1,Claude Opus 4.5,200k,Anthropic,49,$10.00,79,1.70
2,Gemini 3 Pro Preview (high),1m,Google,48,$4.50,128,32.19
3,GPT-5.1 (high),400k,OpenAI,47,$3.44,127,26.50
4,Gemini 3 Flash,1m,Google,46,$1.13,224,11.62